#=========================== Filebeat inputs =============================

filebeat.inputs:
- type: log
  # Change to true to enable this input configuration.
  enabled: true
  # Paths that should be crawled and fetched. Glob based paths.
  paths:
    - /opt/apache-tomcat-ext/logs/pay-oss-ext.log
  fields:
    appname: pay-oss-ext
#============================= Filebeat modules ===============================

filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: false

  # Period on which files under path should be checked for changes
  #reload.period: 10s


#-------------------------- Kafka output ------------------------------
output.kafka:
  # initial brokers for reading cluster metadata
  hosts: ["119.3.81.101:19092", "119.3.76.12:19092", "119.3.89.1:19092"]

  # message topic selection + partitioning
  topic: pay_oss_ext

  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
#================================ Logging =====================================
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
